//#region UI CONSTANTS
export const UI_FETCHING_TRUE = 'UI_FETCHING_TRUE';
export const UI_FETCHING_FALSE = 'UI_FETCHING_FALSE';
export const UI_SHOW_INFO_ERROR = 'UI_SHOW_INFO_ERROR';
export const UI_SHOW_INFO_SUCCESS = 'UI_SHOW_INFO_SUCCESS';
export const UI_CLOSE_INFO = 'UI_CLOSE_INFO';
export const UI_OPEN_DIALOG = 'UI_OPEN_DIALOG';
export const UI_CLOSE_DIALOG = 'UI_CLOSE_DIALOG';
export const UI_OPEN_DELETE_DIALOG = 'UI_OPEN_DELETE_DIALOG';
export const UI_CLOSE_DELETE_DIALOG = 'UI_CLOSE_DELETE_DIALOG';
//#endregion

//#region USER CONSTANTS
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_ADD_TOKEN = 'USER_ADD_TOKEN';
//#endregion


//#region CATEGORY CONSTANTS
export const CATEGORY_ADD = 'CATEGORY_ADD';
export const CATEGORY_EDIT = 'CATEGORY_EDIT';
export const CATEGORY_FETCH_ALL = 'CATEGORY_FETCH_ALL';
//#endregion
