//#region UI CONSTANTS
export const UI_FETCHING_TRUE = 'UI_FETCHING_TRUE';
export const UI_FETCHING_FALSE = 'UI_FETCHING_FALSE';
export const UI_SHOW_INFO_ERROR = 'UI_SHOW_INFO_ERROR';
export const UI_SHOW_INFO_SUCCESS = 'UI_SHOW_INFO_SUCCESS';
export const UI_CLOSE_INFO = 'UI_CLOSE_INFO';
export const UI_KEEP_DIALOG_OPEN = 'UI_KEEP_DIALOG_OPEN';
//#endregion

//#region USER CONSTANTS
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_ADD_TOKEN = 'USER_ADD_TOKEN';
//#endregion


//#region CATEGORY CONSTANTS
export const CATEGORY_FETCH_ALL = 'CATEGORY_FETCH_ALL';
export const CATEGORY_CREATE = 'CATEGORY_CREATE';
export const CATEGORY_EDIT = 'CATEGORY_EDIT';
export const CATEGORY_DELETE = 'CATEGORY_DELETE';
export const CATEGORY_CLOSE_CREATE_EDIT_DIALOG = 'CATEGORY_CLOSE_CREATE_EDIT_DIALOG';
export const CATEGORY_ADD_ITEM = 'CATEGORY_ADD_ITEM';
export const CATEGORY_EDIT_ITEM = 'CATEGORY_EDIT_ITEM';
export const CATEGORY_DELETE_ITEM = 'CATEGORY_DELETE_ITEM';
export const CATEGORY_CLOSE_CREATE_EDIT_ITEM_DIALOG = 'CATEGORY_CLOSE_CREATE_EDIT_ITEM_DIALOG';
export const CATEGORY_CLOSE_DELETE_DIALOG = 'CATEGORY_CLOSE_DELETE_DIALOG';
//#endregion

//#region SHOPPING_LIST CONSTANTS
export const SHOPPING_LIST_FETCH_ALL = 'SHOPPING_LIST_FETCH_ALL';
export const SHOPPING_LIST_CREATE_OPEN = 'SHOPPING_LIST_CREATE_OPEN';
export const SHOPPING_LIST_CREATE_EDIT_CLOSE = 'SHOPPING_LIST_CREATE_EDIT_CLOSE';
export const SHOPPING_LIST_FETCHING_CATEGORIES_TRUE = 'SHOPPING_LIST_FETCHING_CATEGORIES_TRUE';
export const SHOPPING_LIST_FETCHING_CATEGORIES_FALSE = 'SHOPPING_LIST_FETCHING_CATEGORIES_FALSE';
export const SHOPPING_LIST_FETCH_ALL_SUCCESS = 'SHOPPING_LIST_FETCH_ALL_SUCCESS';
export const SHOPPING_LIST_EDIT_OPEN = 'SHOPPING_LIST_EDIT_OPEN';
export const SHOPPING_LIST_DELETE_OPEN = 'SHOPPING_LIST_DELETE_OPEN';
export const SHOPPING_LIST_DELETE_SUCCESS = 'SHOPPING_LIST_DELETE_SUCCESS';
export const SHOPPING_LIST_PURCHASES_DIALOG_OPEN = 'SHOPPING_LIST_PURCHASES_DIALOG_OPEN';
export const SHOPPING_LIST_PURCHASES_DIALOG_CLOSE = 'SHOPPING_LIST_PURCHASES_DIALOG_CLOSE';
export const SHOPPING_LIST_PURCHASES_SORT_UNSELECTED_ITEMS = 'SHOPPING_LIST_PURCHASES_SORT_UNSELECTED_ITEMS';
export const SHOPPING_LIST_PURCHASES_SORT_SELECTED_ITEMS = 'SHOPPING_LIST_PURCHASES_SORT_SELECTED_ITEMS';
export const SHOPPING_LIST_PURCHASES_ADD_ITEMS = 'SHOPPING_LIST_PURCHASES_ADD_ITEMS';
export const SHOPPING_LIST_PURCHASES_REMOVE_ITEMS = 'SHOPPING_LIST_PURCHASES_REMOVE_ITEMS';
export const SHOPPING_LIST_PURCHASES_CHANGE_QUANTITY_UNSELECTED_LIST = 'SHOPPING_LIST_PURCHASES_CHANGE_QUANTITY_UNSELECTED_LIST';
export const SHOPPING_LIST_PURCHASES_CHANGE_QUANTITY_SELECTED_LIST = 'SHOPPING_LIST_PURCHASES_CHANGE_QUANTITY_SELECTED_LIST';
export const SHOPPING_LIST_PURCHASES_CHECK_ITEM_TO_ADD = 'SHOPPING_LIST_PURCHASES_CHECK_ITEM_TO_ADD';
export const SHOPPING_LIST_PURCHASES_CHECK_ITEM_TO_REMOVE = 'SHOPPING_LIST_PURCHASES_CHECK_ITEM_TO_REMOVE';
export const SHOPPING_LIST_PURCHASES_SHOPPING_MODE_COLLECT_ITEM = 'SHOPPING_LIST_PURCHASES_SHOPPING_MODE_COLLECT_ITEM';
export const SHOPPING_LIST_PURCHASES_SHOPPING_MODE_START = 'SHOPPING_LIST_PURCHASES_SHOPPING_MODE_START';
export const SHOPPING_LIST_PURCHASES_SHOPPING_MODE_FINISH = 'SHOPPING_LIST_PURCHASES_SHOPPING_MODE_FINISH';
export const SHOPPING_LIST_PURCHASES_SHOPPING_MODE_SELECT = 'SHOPPING_LIST_PURCHASES_SHOPPING_MODE_SELECT';
//#endregion
